# Generated by Django 5.0 on 2024-01-06 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_remove_profile_follower_profile_followers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
    ]
