# Generated by Django 5.0 on 2024-01-08 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_dog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dog',
        ),
    ]
