# Generated by Django 5.0 on 2024-01-09 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userprofile", "0016_conversation_message_notification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="conversation",
        ),
        migrations.RemoveField(
            model_name="usermessage",
            name="receiver",
        ),
        migrations.RemoveField(
            model_name="usermessage",
            name="sender",
        ),
        migrations.AddField(
            model_name="message",
            name="receiver",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_messages",
                to="userprofile.profile",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to="userprofile.profile",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.TextField(default="SOME STRING"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="userprofile.profile"
            ),
        ),
        migrations.DeleteModel(
            name="Conversation",
        ),
        migrations.DeleteModel(
            name="UserMessage",
        ),
    ]
